[wikiInfo]
WikiName="helloWiki"
[dataBase]
Location="db"
DefaultDBName="hellowikiBase.db"
[searchDB]
Location="index"
DefaultIndex="unclassified_articles"
[dirDB]
Location="content"
DefaultDir="unclassified_articles"
[server]
AppMode="debug"
Port=":8080"
[analyze]
Dict="embed, zh"
[dataDir]
Location="./data/"
